import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:koopy/components/home/lists/ListsController.dart';

class Lists extends StatelessWidget {
  const Lists({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    ListsController c = Get.put(ListsController());

    return Obx(
      () => GestureDetector(
        onPanUpdate: (value) {
          if (value.delta.dx < -15) {
            c.closeDrawer();
          } else if (value.delta.dx > 15) {
            c.openDrawer();
          }
        },
        child: AnimatedContainer(
          duration: Duration(milliseconds: 200),
          height: c.height,
          width: c.width,
          transform: Matrix4.translationValues(
            c.transform['translateX']!,
            c.transform['translateY']!,
            0,
          )..scale(c.transform['scale']),
          curve: Curves.easeInOutCubic,
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(c.transform['radius']!),
            boxShadow: [
              BoxShadow(
                color: Colors.black26,
                blurRadius: 10,
                spreadRadius: 10,
              ),
            ],
          ),
          child: ListView(
            children: [
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
              Text("asd"),
            ],
          ),
        ),
      ),
    );
  }
}
